qmt:
  path: E:\gj_qmt\bin.x64
  market: 沪深A股
database:
  host: 192.168.3.118
  port: 33306
  user: qmt_db
  password: RZmfGsKPTrNHebW6
  database: qmt_db
monitor:
  stocks:
  - 000001.SZ
  - 600036.SH
  - 000300.SH
  timeframes:
  - 1m
  - 5m
  - 15m
  - 30m
  - 1h
  - 1d
  - 1w
  - 1mon
  interval: 15
web:
  host: 0.0.0.0
  port: 8000